name: Publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test:ci
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
